"""unified initial schema

Revision ID: d76f5d277546
Revises: 
Create Date: 2026-09-13 09:31:42.346637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 - referenced by autogenerated JSONB(astext_type=Text()) columns
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd76f5d277546'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('base', sa.String(length=8), nullable=False),
    sa.Column('quote', sa.String(length=8), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base', 'quote', 'as_of', name='uq_fx_base_quote_as_of')
    )
    op.create_index('ix_fx_pair_as_of', 'fx_rates', ['base', 'quote', 'as_of'], unique=False)
    op.create_table('market_providers',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('env_var', sa.String(length=120), nullable=True),
    sa.Column('license_note', sa.String(length=500), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('circuit_state', sa.String(length=12), nullable=False),
    sa.Column('disabled_reason', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("circuit_state in ('closed','open','half_open')", name='ck_market_provider_circuit'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('providers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('license_note', sa.String(length=500), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('circuit_state', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("circuit_state in ('closed','open','half_open')", name='ck_provider_circuit_state'),
    sa.CheckConstraint("type in ('rss','json_api','calendar_ics')", name='ck_provider_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('reference_currency', sa.String(length=8), nullable=False),
    sa.Column('display_timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("status in ('running','success','partial','failed')", name='ck_run_status'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_provider_started', 'ingestion_runs', ['provider_id', 'started_at'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_symbol', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("asset_class in ('action', 'etf', 'crypto', 'obligation', 'actif_prive', 'indice', 'devise')", name='ck_instrument_asset_class'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_symbol', name='uq_instrument_provider_symbol'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_instrument_user_symbol')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    op.create_index(op.f('ix_instruments_user_id'), 'instruments', ['user_id'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('excerpt', sa.String(length=2000), nullable=True),
    sa.Column('summary', sa.String(length=2000), nullable=True),
    sa.Column('publication_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('citation', sa.String(length=500), nullable=True),
    sa.Column('provenance', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('relevance_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('freshness_at_collection', sa.String(length=12), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("category in ('resultats','dividende','reglementation','operation_titre','gouvernance','marche','macro','autre')", name='ck_news_category'),
    sa.CheckConstraint("kind in ('fact','synthesis','prediction')", name='ck_news_kind'),
    sa.CheckConstraint("verification_status in ('unverified','corroborated','corrected','retracted')", name='ck_news_verification_status'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_content_hash'), 'news_items', ['content_hash'], unique=False)
    op.create_index('ix_news_provider_hash', 'news_items', ['provider_id', 'content_hash'], unique=False)
    op.create_index('ix_news_publication_at', 'news_items', ['publication_at'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('portfolio_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('event_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_event_user_created', 'audit_events', ['user_id', 'created_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_label', sa.String(length=40), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint("status in ('confirme','previsionnel','reporte','annule','unknown')", name='ck_event_status'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_instrument_starts', 'events', ['instrument_id', 'starts_at'], unique=False)
    op.create_index(op.f('ix_events_content_hash'), 'events', ['content_hash'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('portfolio_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=260), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('delimiter', sa.String(length=4), nullable=False),
    sa.Column('encoding', sa.String(length=40), nullable=False),
    sa.Column('column_mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('default_timezone', sa.String(length=40), nullable=False),
    sa.Column('raw_rows', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('row_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('draft', 'previewed', 'committed')", name='ck_import_job_status'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_portfolio_id'), 'import_jobs', ['portfolio_id'], unique=False)
    op.create_table('news_item_instruments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('news_item_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_id', 'instrument_id', name='uq_news_item_instrument')
    )
    op.create_table('news_item_relations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('news_item_id', sa.String(length=32), nullable=False),
    sa.Column('related_news_item_id', sa.String(length=32), nullable=False),
    sa.Column('relation_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("relation_type in ('duplicate_of','corroborates')", name='ck_relation_type'),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_id', 'related_news_item_id', 'relation_type', name='uq_news_relation')
    )
    op.create_table('ohlc_bars',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('volume', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('low IS NULL OR high IS NULL OR low <= high', name='ck_ohlc_low_le_high'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'interval', 'as_of', name='uq_ohlc_instrument_interval_as_of')
    )
    op.create_index(op.f('ix_ohlc_bars_instrument_id'), 'ohlc_bars', ['instrument_id'], unique=False)
    op.create_table('prediction_experiments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('code_version', sa.String(length=40), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=True),
    sa.Column('dataset_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('folds', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('predictions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('latest_forecast', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('pending', 'running', 'completed', 'failed')", name='ck_prediction_status'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_experiments_user_id'), 'prediction_experiments', ['user_id'], unique=False)
    op.create_table('price_points',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_point_instrument_as_of', 'price_points', ['instrument_id', 'as_of'], unique=False)
    op.create_index(op.f('ix_price_points_instrument_id'), 'price_points', ['instrument_id'], unique=False)
    op.create_table('private_valuations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('valuation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valuation_amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('method', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_valuations_instrument_id'), 'private_valuations', ['instrument_id'], unique=False)
    op.create_table('provider_feeds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('extra_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('portfolio_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fees', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('account', sa.String(length=80), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type in ('achat', 'vente', 'dividende', 'coupon', 'depot', 'retrait', 'transfert', 'split', 'valorisation_privee')", name='ck_transaction_type'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'external_id', name='uq_transaction_portfolio_external_id')
    )
    op.create_index('ix_transaction_portfolio_trade_date', 'transactions', ['portfolio_id', 'trade_date'], unique=False)
    op.create_index(op.f('ix_transactions_portfolio_id'), 'transactions', ['portfolio_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'instrument_id', name='uq_watchlist_user_instrument')
    )
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    op.create_table('event_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('citation', sa.String(length=500), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_status_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('old_status', sa.String(length=16), nullable=True),
    sa.Column('new_status', sa.String(length=16), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_lots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('portfolio_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity_remaining', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_lots_instrument_id'), 'position_lots', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_position_lots_portfolio_id'), 'position_lots', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_lots_portfolio_id'), table_name='position_lots')
    op.drop_index(op.f('ix_position_lots_instrument_id'), table_name='position_lots')
    op.drop_table('position_lots')
    op.drop_table('event_status_history')
    op.drop_table('event_sources')
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_transactions_portfolio_id'), table_name='transactions')
    op.drop_index('ix_transaction_portfolio_trade_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('provider_feeds')
    op.drop_index(op.f('ix_private_valuations_instrument_id'), table_name='private_valuations')
    op.drop_table('private_valuations')
    op.drop_index(op.f('ix_price_points_instrument_id'), table_name='price_points')
    op.drop_index('ix_price_point_instrument_as_of', table_name='price_points')
    op.drop_table('price_points')
    op.drop_index(op.f('ix_prediction_experiments_user_id'), table_name='prediction_experiments')
    op.drop_table('prediction_experiments')
    op.drop_index(op.f('ix_ohlc_bars_instrument_id'), table_name='ohlc_bars')
    op.drop_table('ohlc_bars')
    op.drop_table('news_item_relations')
    op.drop_table('news_item_instruments')
    op.drop_index(op.f('ix_import_jobs_portfolio_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_events_content_hash'), table_name='events')
    op.drop_index('ix_event_instrument_starts', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_audit_event_user_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('ix_news_publication_at', table_name='news_items')
    op.drop_index('ix_news_provider_hash', table_name='news_items')
    op.drop_index(op.f('ix_news_items_content_hash'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_instruments_user_id'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index('ix_run_provider_started', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('providers')
    op.drop_table('market_providers')
    op.drop_index('ix_fx_pair_as_of', table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
