"""add import_jobs

Revision ID: d45747742d9a
Revises: 5fe97d5bc03e
Create Date: 2026-09-13 00:42:30.404884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 - referenced by autogenerated JSONB(astext_type=Text()) columns
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd45747742d9a'
down_revision: Union[str, None] = '5fe97d5bc03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('portfolio_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=260), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('delimiter', sa.String(length=4), nullable=False),
    sa.Column('encoding', sa.String(length=40), nullable=False),
    sa.Column('column_mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('default_timezone', sa.String(length=40), nullable=False),
    sa.Column('raw_rows', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('row_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('draft', 'previewed', 'committed')", name='ck_import_job_status'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_portfolio_id'), 'import_jobs', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_jobs_portfolio_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
